# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Talks
    url: talks
    weight: 30
  - name: People
    url: people
    weight: 20
  - name: Open-Source Projects
    url: open_source_projects
    weight: 10
  - name: Publications
    url: publication
    weight: 50
  - name: Ongoing Projects
    url: ongoing_project
    weight: 55
  - name: Contact
    url: contact
    weight: 60
